# Clambake Configuration Example
# Copy this file to clambake.toml and customize as needed

[github]
# GitHub repository settings
owner = "johnhkchen"
repo = "clambake"

# Rate limiting configuration
[github.rate_limit]
requests_per_hour = 5000
burst_capacity = 100

[observability]
# Enable OpenTelemetry distributed tracing
tracing_enabled = true
# Optional: OTLP endpoint (defaults to stdout export)
# otlp_endpoint = "http://localhost:4317"
# Log level: trace, debug, info, warn, error
log_level = "info"
# Enable metrics collection
metrics_enabled = true

[agents]
# Maximum number of concurrent agents
max_agents = 4
# Agent coordination timeout in seconds
coordination_timeout_seconds = 300

# Bundle processing configuration
[agents.bundle_processing]
max_queue_size = 50
processing_timeout_seconds = 1800

# Optional database configuration
# Uncomment to enable persistent state storage
# [database]
# url = ".clambake/clambake.db"
# max_connections = 10
# auto_migrate = true

# Environment variables can override any setting:
# CLAMBAKE_GITHUB_TOKEN=ghp_xxx...
# CLAMBAKE_GITHUB_OWNER=your-org
# CLAMBAKE_GITHUB_REPO=your-repo
# CLAMBAKE_OBSERVABILITY_LOG_LEVEL=debug
# CLAMBAKE_AGENTS_MAX_AGENTS=8