[github]
owner = "johnhkchen"
repo = "my-little-soda"

[github.rate_limit]
requests_per_hour = 5000
burst_capacity = 100

[observability]
tracing_enabled = true
log_level = "info"
metrics_enabled = true

[agents]
max_agents = 4
coordination_timeout_seconds = 300

[agents.bundle_processing]
max_queue_size = 50
processing_timeout_seconds = 1800

[database]
url = ".my-little-soda/my-little-soda.db"
max_connections = 10
auto_migrate = true
